name: Build LKM for KernelSU
on:
  push:
    branches: ["main", "ci", "checkci"]
    paths:
      - ".github/workflows/gki-kernel.yml"
      - ".github/workflows/build-lkm.yml"
      - "kernel/**"
  pull_request:
    branches: ["main"]
    paths:
      - ".github/workflows/gki-kernel.yml"
      - ".github/workflows/build-lkm.yml"
      - "kernel/**"
  workflow_call:
jobs:
  build-lkm:
    strategy:
      matrix:
        include:
          - version: "android12-5.10"
            sub_level: 198
            os_patch_level: "2024-01"
          - version: "android13-5.10"
            sub_level: 198
            os_patch_level: 2023-12
          - version: "android13-5.15"
            sub_level: 137
            os_patch_level: 2023-12
          - version: "android14-5.15"
            sub_level: 110
            os_patch_level: 2023-09
          - version: "android14-6.1"
            sub_level: 43
            os_patch_level: 2023-11
    uses: ./.github/workflows/gki-kernel.yml
    with:
      version: ${{ matrix.version }}
      version_name: ${{ matrix.version }}.${{ matrix.sub_level }}
      tag: ${{ matrix.version }}-${{ matrix.os_patch_level }}
      os_patch_level: ${{ matrix.os_patch_level }}
      build_lkm: true
  
  upload-artifacts:
    needs: build-lkm
    runs-on: ubuntu-latest
    env:
      CHAT_ID: ${{ secrets.CHAT_ID }}
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      MESSAGE_THREAD_ID: ${{ secrets.MESSAGE_THREAD_ID }}
      COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
      COMMIT_URL: ${{ github.event.head_commit.url }}
      RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
      
      - name: List artifacts
        run: |
          tree